### Import a KML file
# To use this:
# 1. Install the REST Client extension in VS Code
# 2. Update the file path below to point to your KML file
# 3. Click "Send Request"

POST http://localhost:5000/api/import-kml
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="kml"; filename="senatorial.kml"
Content-Type: application/vnd.google-earth.kml+xml

< C:\Users\andyr\Desktop\golf_app_related\courses_scratch\senatorial.kml
------WebKitFormBoundary7MA4YWxkTrZu0gW--

